spring:
  application:
    name: music-server
server:
  servlet:
    context-path: /
  port: 8888
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    com.cmx.music: DEBUG
---
spring:
  profiles: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/cmx_music?userUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: com/cmx/music/dao/xml/*.xml
  type-aliases-package: com.cmx.music.pojo
