server:
  servlet:
    context-path: /
  port: 8888

spring:
  application:
    name: music-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/cmx_music
mybatis:
  type-aliases-package: com.cmx.music.pojo
  mapper-locations: com.cmx.music.dao.xml/*.xml



