server:
  servlet:
    context-path: /
  port: 8888
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    com.cmx.music: DEBUG

spring:
  application:
    name: music-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/cmx_music?userUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: com/cmx/music/dao/xml/*.xml
  type-aliases-package: com.cmx.music.pojo


